require("configs.impatient")

require("configs.bufferline")
require("configs.dressing")
require("configs.gitsigns")
require("configs.lualine")
require("configs.matchup")
require("configs.nvim-autopairs")
require("configs.nvim-colorizer")
require("configs.nvim-tree")
require("configs.nvim-treesitter")
require("configs.telescope")
require("configs.todo-comments")
require("configs.tokyonight")
